In [256]:
import requests
import pandas as pd
import time
import json
import datetime

In [257]:
def OpenAlexAPI(url, params):
    
    # Initialize cursor
    cursor = "*"

    # Create a container
    all_datasets = []
    page = 0
    while cursor:
        params["cursor"] = cursor
        
        # Check for request success
        response = requests.get(url, params=params)
        if response.status_code == 200:
            print(f"Status code: {response.status_code}", ';',  "Page number: ", page)
        if response.status_code != 200:
            print("Oh no! Something went wrong during the live demo! How embarrassing!")
            response.raise_for_status()
        records = response.json()['results']
        
        # create a loop iterator
        record_number = 0
        page += 1
       
       # Loop over all the records
        for record in records:
            record_number += 1
            #print("Page number: ", page, 'Record number:', record_number, record)
            all_datasets.append({'id': record['id'],
                                'doi': record['doi'],
                                'title': record['title'],
                                'type': record['type'],
                                'publication_year': record['publication_year'],
                                'publication_date': record['publication_date'],
                                'primary_topic': record['primary_topic'],
                                'topics': record['topics'][:],
                                'language': record['language'],
                                'retracted': record['is_retracted'],
                                'index location': record['indexed_in'],
                                'primary_location': record['primary_location']['source'],
                                'is_oa': record['open_access']['is_oa'],
                                'oa_status': record['open_access']['oa_status'],
                                'license': record['primary_location']['license'], 
                                'authorships': record['authorships'][:],
                                'affiliations': record['authorships'][0]['affiliations'],
                                'Institution': record['authorships'][0]['institutions'],
                                'apc_list': record['apc_list'],
                                'apc_paid': record['apc_paid'],
                                'fwci': record['fwci'],
                                'has_fulltext': record['has_fulltext'],
                                'cited_by_count': record['cited_by_count'], 
                                'citation_normalized_percentile': record['citation_normalized_percentile'],
                                'cited_by_percentile_year': record['cited_by_percentile_year'],
                                'biblio': record['biblio']
                                })         

        # Update cursor
        cursor = response.json()['meta']['next_cursor']
        
        time.sleep(3)
    return all_datasets

parameters = {
    "per-page": 100,
}

In [258]:
Source_URL = 'https://api.openalex.org/works?page=1&filter=type:dataset,primary_location.source.id:s4306402521|s7407053140'
Source_JSONOutFile = str(datetime.datetime.today()).split()[0] + '-Source.json'
with open(Source_JSONOutFile, 'w') as outfile:
    json.dump(OpenAlexAPI(Source_URL, parameters), outfile)

Status code: 200 ; Page number:  0
Status code: 200 ; Page number:  1
Status code: 200 ; Page number:  2
Status code: 200 ; Page number:  3
Status code: 200 ; Page number:  4
Status code: 200 ; Page number:  5
Status code: 200 ; Page number:  6
Status code: 200 ; Page number:  7
Status code: 200 ; Page number:  8

In [259]:
# Function that creates new dataframe from nested list
def CleanJSON(column,InputDF):
    df = pd.concat([pd.DataFrame(x) for x in InputDF[column]], keys=InputDF.index).reset_index(level=1,drop=True)
    return df

In [260]:
def missing_index(df):
    missing_indices = ([i for i in range(0, len(df)) if i not in df.index])
    return missing_indices

In [261]:
pd.set_option("display.max_columns", 55)

In [262]:
df = pd.read_json(Source_JSONOutFile)
df.head()

,id,doi,title,type,publication_year,publication_date,primary_topic,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authorships,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,Minnesota Solvation Database (MNSOL) version 2012,dataset,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,[datacite],"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,cc-by-nc-nd,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,41,None,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
1,https://openalex.org/W2297941261,https://doi.org/10.13020/d6g014,White-tailed deer density estimates across the...,dataset,2016,2016-01-01,"{'id': 'https://openalex.org/T10199', 'display...","[{'id': 'https://openalex.org/T10199', 'displa...",en,False,[datacite],"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,28,None,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
2,https://openalex.org/W2898833073,https://doi.org/10.13020/d6kx2r,Global nitrogen deposition (2°×2.5° grid resol...,dataset,2018,2018-01-01,"{'id': 'https://openalex.org/T11588', 'display...","[{'id': 'https://openalex.org/T11588', 'displa...",en,False,[datacite],"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,17,None,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
3,https://openalex.org/W2525336510,https://doi.org/10.13020/d6jp4s,Minnesota Land Cover Classification and Imperv...,dataset,2016,2016-01-01,"{'id': 'https://openalex.org/T13388', 'display...","[{'id': 'https://openalex.org/T13388', 'displa...",en,False,[datacite],"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,public-domain,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,12,None,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
4,https://openalex.org/W3043928535,https://doi.org/10.13020/g1gx-y834,TrashCan 1.0 An Instance-Segmentation Labeled ...,dataset,2019,2019-06-24,"{'id': 'https://openalex.org/T12039', 'display...","[{'id': 'https://openalex.org/T12039', 'displa...",en,False,[datacite],"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,12,None,NaN,"{'volume': None, 'issue': None, 'first_page': ..."

In [263]:
# investigate the columns
df.columns

Index(['id', 'doi', 'title', 'type', 'publication_year', 'publication_date',
       'primary_topic', 'topics', 'language', 'retracted', 'index location',
       'primary_location', 'is_oa', 'oa_status', 'license', 'authorships',
       'affiliations', 'Institution', 'apc_list', 'apc_paid', 'fwci',
       'has_fulltext', 'cited_by_count', 'citation_normalized_percentile',
       'cited_by_percentile_year', 'biblio'],
      dtype='object')

In [264]:
# Remove list element from column
df['index location'] = df['index location'].str[0]
df

,id,doi,title,type,publication_year,publication_date,primary_topic,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authorships,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,Minnesota Solvation Database (MNSOL) version 2012,dataset,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,cc-by-nc-nd,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,41,None,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
1,https://openalex.org/W2297941261,https://doi.org/10.13020/d6g014,White-tailed deer density estimates across the...,dataset,2016,2016-01-01,"{'id': 'https://openalex.org/T10199', 'display...","[{'id': 'https://openalex.org/T10199', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,28,None,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
2,https://openalex.org/W2898833073,https://doi.org/10.13020/d6kx2r,Global nitrogen deposition (2°×2.5° grid resol...,dataset,2018,2018-01-01,"{'id': 'https://openalex.org/T11588', 'display...","[{'id': 'https://openalex.org/T11588', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,17,None,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
3,https://openalex.org/W2525336510,https://doi.org/10.13020/d6jp4s,Minnesota Land Cover Classification and Imperv...,dataset,2016,2016-01-01,"{'id': 'https://openalex.org/T13388', 'display...","[{'id': 'https://openalex.org/T13388', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,public-domain,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,12,None,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
4,https://openalex.org/W3043928535,https://doi.org/10.13020/g1gx-y834,TrashCan 1.0 An Instance-Segmentation Labeled ...,dataset,2019,2019-06-24,"{'id': 'https://openalex.org/T12039', 'display...","[{'id': 'https://openalex.org/T12039', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,12,None,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,https://openalex.org/W7137012762,https://doi.org/10.13020/m0g4-ac20,"Data for ""Effect of water suppression and meta...",dataset,2026,2026-01-01,None,[],None,False,datacite,"{'id': 'https://openalex.org/S7407053140', 'di...",True,green,public-domain,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I2800403580', 'd...",NaN,NaN,NaN,False,0,None,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
732,https://openalex.org/W7140099683,https://doi.org/10.13020/qn0g-0564,Supporting data for Probing Phonon Mean-Free-P...,dataset,2026,2026-01-01,None,[],None,False,datacite,"{'id': 'https://openalex.org/S7407053140', 'di...",True,green,public-domain,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I2800403580', 'd...",NaN,NaN,NaN,False,0,None,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
733,https://openalex.org/W830385225,None,"C-35, Geologic Atlas of Meeker County, Minneso...",dataset,2015,2015-01-01,"{'id': 'https://openalex.org/T13939', 'display...","[{'id': 'https://openalex.org/T13939', 'displa...",en,False,NaN,"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,True,0,None,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
734,https://openalex.org/W89491114,None,Tracking of references with varying frequency,dataset,2014,2014-09-30,"{'id': 'https://openalex.org/T12031', 'display...","[{'id': 'https://openalex.org/T12031', 'displa...",en,False,NaN,"{'id': 'https://openalex.org/S4306402521', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,0,None,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
735,https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,"Solar Insolation, Minnesota (2006-2012)",dataset,2015,2015-06-29,"{'id': 'https://openalex.org/T11276', 'display...","[{'id': 'https://openalex.org/T11276', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,cc-by,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,0,None,NaN,"{'volume': None, 'issue': None, 'first_page': ..."

In [265]:
# normalize  citation metric columns data

citation_normalized_percentile_df = pd.json_normalize(df['citation_normalized_percentile'])
cited_by_percentile_year_df = pd.json_normalize(df['cited_by_percentile_year'])
biblio_df = pd.json_normalize(df['biblio'])
# concat normalized data into original df

df = pd.concat([df, citation_normalized_percentile_df], axis=1)
df = pd.concat([df, cited_by_percentile_year_df], axis=1)
df = pd.concat([df, biblio_df], axis=1)

#rename column
df = df.rename(columns={'value': 'citation_normalized_percentile-value'})


df.head()

,id,doi,title,type,publication_year,publication_date,primary_topic,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authorships,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio,citation_normalized_percentile-value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,Minnesota Solvation Database (MNSOL) version 2012,dataset,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,cc-by-nc-nd,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,41,None,NaN,"{'volume': None, 'issue': None, 'first_page': ...",NaN,NaN,NaN,None,None,None,None
1,https://openalex.org/W2297941261,https://doi.org/10.13020/d6g014,White-tailed deer density estimates across the...,dataset,2016,2016-01-01,"{'id': 'https://openalex.org/T10199', 'display...","[{'id': 'https://openalex.org/T10199', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,28,None,NaN,"{'volume': None, 'issue': None, 'first_page': ...",NaN,NaN,NaN,None,None,None,None
2,https://openalex.org/W2898833073,https://doi.org/10.13020/d6kx2r,Global nitrogen deposition (2°×2.5° grid resol...,dataset,2018,2018-01-01,"{'id': 'https://openalex.org/T11588', 'display...","[{'id': 'https://openalex.org/T11588', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,17,None,NaN,"{'volume': None, 'issue': None, 'first_page': ...",NaN,NaN,NaN,None,None,None,None
3,https://openalex.org/W2525336510,https://doi.org/10.13020/d6jp4s,Minnesota Land Cover Classification and Imperv...,dataset,2016,2016-01-01,"{'id': 'https://openalex.org/T13388', 'display...","[{'id': 'https://openalex.org/T13388', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,public-domain,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,12,None,NaN,"{'volume': None, 'issue': None, 'first_page': ...",NaN,NaN,NaN,None,None,None,None
4,https://openalex.org/W3043928535,https://doi.org/10.13020/g1gx-y834,TrashCan 1.0 An Instance-Segmentation Labeled ...,dataset,2019,2019-06-24,"{'id': 'https://openalex.org/T12039', 'display...","[{'id': 'https://openalex.org/T12039', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,12,None,NaN,"{'volume': None, 'issue': None, 'first_page': ...",NaN,NaN,NaN,None,None,None,None

In [266]:
# normalize columns data
primary_location_df = pd.json_normalize(df['primary_location'])


# extract only display name column
primary_location_df = primary_location_df[['display_name']]

#rename display name column
primary_location_df = primary_location_df.rename(columns={'display_name': 'primary_location-source-display_name'}) 

#primary_location_df = primary_location_df.reindex(range(primary_location_df.index.min(), primary_location_df .index.max()+1))

# concat display name column to main df
df = pd.concat([df, primary_location_df], axis=1)

In [267]:
# Use function to normalize Authors nested list
authorships_df = CleanJSON('authorships', df)
authorships_df['raw_affiliation_strings'] = authorships_df['raw_affiliation_strings'].str[0]
authorships_df

,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations
0,first,"{'id': 'https://openalex.org/A5061017744', 'di...",[],[],True,"Marenich, Aleksandr V",NaN,[]
0,middle,"{'id': 'https://openalex.org/A5053083096', 'di...",[],[],False,"Kelly, Casey P",NaN,[]
0,middle,"{'id': 'https://openalex.org/A5111863630', 'di...",[],[],False,"Thompson, Jason D",NaN,[]
0,middle,"{'id': 'https://openalex.org/A5113505750', 'di...",[],[],False,"Hawkins, Gregory D",NaN,[]
0,middle,"{'id': 'https://openalex.org/A5110699802', 'di...",[],[],False,"Chambers, Candy C",NaN,[]
...,...,...,...,...,...,...,...,...
735,middle,"{'id': 'https://openalex.org/A5019127857', 'di...",[],[],False,"Palka, Stephen",NaN,[]
735,middle,"{'id': 'https://openalex.org/A5048502234', 'di...",[],[],False,"Piernot, Devon",NaN,[]
735,middle,"{'id': 'https://openalex.org/A5006917855', 'di...",[],[],False,"Thiede, Dan",NaN,[]
735,middle,"{'id': 'https://openalex.org/A5007673815', 'di...",[],[],False,"Xie, Yiquan",NaN,[]
735,last,"{'id': 'https://openalex.org/A5025818352', 'di...",[],[],False,"Walz, Andrew",NaN,[]

In [268]:
missing_index(authorships_df['raw_affiliation_strings'])

[736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 1001,
 1002,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 1009,
 1010,
 1011,
 1012,
 1013,
 1014,
 1015,
 1016,
 1017,
 1018,
 1019,
 1020,
 1021,
 1022,
 1023,
 1024,
 1025,
 1026,
 1027,
 1028,
 1029,
 1030,
 1031,
 1032,
 1033,
 1034,
 1035,
 1036,
 1037,
 1038,
 1039,
 1040,
 1041,
 1042,
 1043,
 1044,
 1045,
 1046,
 1047,
 1048,
 1049,
 1050,
 1051,
 1052,
 1053,
 1054,
 1055,
 1056,
 1057,
 1058,
 1059,
 1060,
 1061,
 1062,
 1063,
 1064,
 1065,
 1066,
 1067,
 1068,
 1069,
 1070,
 1071,
 1072,
 1073,
 1074,
 1075,
 1076,
 1077,
 1078,
 1079,
 1080,
 1081,
 1082,
 1083,
 1084,
 1085,
 1086,
 1087,
 1088,
 1089,
 1090,
 1091,
 1092,
 1093,
 1094,
 1095,
 1096,
 1097,
 1098,
 1099,
 1100,
 1101,
 1102,
 1103,
 1104,
 1105,
 1106,
 1107,
 1108,
 1109,
 1110,
 1111,
 1112,
 1113,
 1114,
 1115,
 1116,
 1117,
 1118,
 1119,
 1120,
 1121,
 1122,
 1123,
 1124,
 1125,
 1126,
 1127,
 1128,
 1129,
 1130,
 1131,
 1132,
 1133,
 1134,
 1135,
 1136,
 1137,
 1138,
 1139,
 1140,
 1141,
 1142,
 1143,
 1144,
 1145,
 1146,
 1147,
 1148,
 1149,
 1150,
 1151,
 1152,
 1153,
 1154,
 1155,
 1156,
 1157,
 1158,
 1159,
 1160,
 1161,
 1162,
 1163,
 1164,
 1165,
 1166,
 1167,
 1168,
 1169,
 1170,
 1171,
 1172,
 1173,
 1174,
 1175,
 1176,
 1177,
 1178,
 1179,
 1180,
 1181,
 1182,
 1183,
 1184,
 1185,
 1186,
 1187,
 1188,
 1189,
 1190,
 1191,
 1192,
 1193,
 1194,
 1195,
 1196,
 1197,
 1198,
 1199,
 1200,
 1201,
 1202,
 1203,
 1204,
 1205,
 1206,
 1207,
 1208,
 1209,
 1210,
 1211,
 1212,
 1213,
 1214,
 1215,
 1216,
 1217,
 1218,
 1219,
 1220,
 1221,
 1222,
 1223,
 1224,
 1225,
 1226,
 1227,
 1228,
 1229,
 1230,
 1231,
 1232,
 1233,
 1234,
 1235,
 1236,
 1237,
 1238,
 1239,
 1240,
 1241,
 1242,
 1243,
 1244,
 1245,
 1246,
 1247,
 1248,
 1249,
 1250,
 1251,
 1252,
 1253,
 1254,
 1255,
 1256,
 1257,
 1258,
 1259,
 1260,
 1261,
 1262,
 1263,
 1264,
 1265,
 1266,
 1267,
 1268,
 1269,
 1270,
 1271,
 1272,
 1273,
 1274,
 1275,
 1276,
 1277,
 1278,
 1279,
 1280,
 1281,
 1282,
 1283,
 1284,
 1285,
 1286,
 1287,
 1288,
 1289,
 1290,
 1291,
 1292,
 1293,
 1294,
 1295,
 1296,
 1297,
 1298,
 1299,
 1300,
 1301,
 1302,
 1303,
 1304,
 1305,
 1306,
 1307,
 1308,
 1309,
 1310,
 1311,
 1312,
 1313,
 1314,
 1315,
 1316,
 1317,
 1318,
 1319,
 1320,
 1321,
 1322,
 1323,
 1324,
 1325,
 1326,
 1327,
 1328,
 1329,
 1330,
 1331,
 1332,
 1333,
 1334,
 1335,
 1336,
 1337,
 1338,
 1339,
 1340,
 1341,
 1342,
 1343,
 1344,
 1345,
 1346,
 1347,
 1348,
 1349,
 1350,
 1351,
 1352,
 1353,
 1354,
 1355,
 1356,
 1357,
 1358,
 1359,
 1360,
 1361,
 1362,
 1363,
 1364,
 1365,
 1366,
 1367,
 1368,
 1369,
 1370,
 1371,
 1372,
 1373,
 1374,
 1375,
 1376,
 1377,
 1378,
 1379,
 1380,
 1381,
 1382,
 1383,
 1384,
 1385,
 1386,
 1387,
 1388,
 1389,
 1390,
 1391,
 1392,
 1393,
 1394,
 1395,
 1396,
 1397,
 1398,
 1399,
 1400,
 1401,
 1402,
 1403,
 1404,
 1405,
 1406,
 1407,
 1408,
 1409,
 1410,
 1411,
 1412,
 1413,
 1414,
 1415,
 1416,
 1417,
 1418,
 1419,
 1420,
 1421,
 1422,
 1423,
 1424,
 1425,
 1426,
 1427,
 1428,
 1429,
 1430,
 1431,
 1432,
 1433,
 1434,
 1435,
 1436,
 1437,
 1438,
 1439,
 1440,
 1441,
 1442,
 1443,
 1444,
 1445,
 1446,
 1447,
 1448,
 1449,
 1450,
 1451,
 1452,
 1453,
 1454,
 1455,
 1456,
 1457,
 1458,
 1459,
 1460,
 1461,
 1462,
 1463,
 1464,
 1465,
 1466,
 1467,
 1468,
 1469,
 1470,
 1471,
 1472,
 1473,
 1474,
 1475,
 1476,
 1477,
 1478,
 1479,
 1480,
 1481,
 1482,
 1483,
 1484,
 1485,
 1486,
 1487,
 1488,
 1489,
 1490,
 1491,
 1492,
 1493,
 1494,
 1495,
 1496,
 1497,
 1498,
 1499,
 1500,
 1501,
 1502,
 1503,
 1504,
 1505,
 1506,
 1507,
 1508,
 1509,
 1510,
 1511,
 1512,
 1513,
 1514,
 1515,
 1516,
 1517,
 1518,
 1519,
 1520,
 1521,
 1522,
 1523,
 1524,
 1525,
 1526,
 1527,
 1528,
 1529,
 1530,
 1531,
 1532,
 1533,
 1534,
 1535,
 1536,
 1537,
 1538,
 1539,
 1540,
 1541,
 1542,
 1543,
 1544,
 1545,
 1546,
 1547,
 1548,
 1549,
 1550,
 1551,
 1552,
 1553,
 1554,
 1555,
 1556,
 1557,
 1558,
 1559,
 1560,
 1561,
 1562,
 1563,
 1564,
 1565,
 1566,
 1567,
 1568,
 1569,
 1570,
 1571,
 1572,
 1573,
 1574,
 1575,
 1576,
 1577,
 1578,
 1579,
 1580,
 1581,
 1582,
 1583,
 1584,
 1585,
 1586,
 1587,
 1588,
 1589,
 1590,
 1591,
 1592,
 1593,
 1594,
 1595,
 1596,
 1597,
 1598,
 1599,
 1600,
 1601,
 1602,
 1603,
 1604,
 1605,
 1606,
 1607,
 1608,
 1609,
 1610,
 1611,
 1612,
 1613,
 1614,
 1615,
 1616,
 1617,
 1618,
 1619,
 1620,
 1621,
 1622,
 1623,
 1624,
 1625,
 1626,
 1627,
 1628,
 1629,
 1630,
 1631,
 1632,
 1633,
 1634,
 1635,
 1636,
 1637,
 1638,
 1639,
 1640,
 1641,
 1642,
 1643,
 1644,
 1645,
 1646,
 1647,
 1648,
 1649,
 1650,
 1651,
 1652,
 1653,
 1654,
 1655,
 1656,
 1657,
 1658,
 1659,
 1660,
 1661,
 1662,
 1663,
 1664,
 1665,
 1666,
 1667,
 1668,
 1669,
 1670,
 1671,
 1672,
 1673,
 1674,
 1675,
 1676,
 1677,
 1678,
 1679,
 1680,
 1681,
 1682,
 1683,
 1684,
 1685,
 1686,
 1687,
 1688,
 1689,
 1690,
 1691,
 1692,
 1693,
 1694,
 1695,
 1696,
 1697,
 1698,
 1699,
 1700,
 1701,
 1702,
 1703,
 1704,
 1705,
 1706,
 1707,
 1708,
 1709,
 1710,
 1711,
 1712,
 1713,
 1714,
 1715,
 1716,
 1717,
 1718,
 1719,
 1720,
 1721,
 1722,
 1723,
 1724,
 1725,
 1726,
 1727,
 1728,
 1729,
 1730,
 1731,
 1732,
 1733,
 1734,
 1735,
 ...]

In [269]:
authorships_df.iloc[736]

author_position                                                        first
author                     {'id': 'https://openalex.org/A5060292512', 'di...
institutions                                                              []
countries                                                                 []
is_corresponding                                                        True
raw_author_name               Lee, Norman; Schrode, Katrina, M; Bee, Mark, A
raw_affiliation_strings                                                  NaN
affiliations                                                              []
Name: 248, dtype: object

In [270]:
df.columns

Index(['id', 'doi', 'title', 'type', 'publication_year', 'publication_date',
       'primary_topic', 'topics', 'language', 'retracted', 'index location',
       'primary_location', 'is_oa', 'oa_status', 'license', 'authorships',
       'affiliations', 'Institution', 'apc_list', 'apc_paid', 'fwci',
       'has_fulltext', 'cited_by_count', 'citation_normalized_percentile',
       'cited_by_percentile_year', 'biblio',
       'citation_normalized_percentile-value', 'is_in_top_1_percent',
       'is_in_top_10_percent', 'volume', 'issue', 'first_page', 'last_page',
       'primary_location-source-display_name'],
      dtype='object')

In [271]:
df.head()

,id,doi,title,type,publication_year,publication_date,primary_topic,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authorships,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio,citation_normalized_percentile-value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page,primary_location-source-display_name
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,Minnesota Solvation Database (MNSOL) version 2012,dataset,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,cc-by-nc-nd,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,41,None,NaN,"{'volume': None, 'issue': None, 'first_page': ...",NaN,NaN,NaN,None,None,None,None,University of Minnesota Digital Conservancy (U...
1,https://openalex.org/W2297941261,https://doi.org/10.13020/d6g014,White-tailed deer density estimates across the...,dataset,2016,2016-01-01,"{'id': 'https://openalex.org/T10199', 'display...","[{'id': 'https://openalex.org/T10199', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,28,None,NaN,"{'volume': None, 'issue': None, 'first_page': ...",NaN,NaN,NaN,None,None,None,None,University of Minnesota Digital Conservancy (U...
2,https://openalex.org/W2898833073,https://doi.org/10.13020/d6kx2r,Global nitrogen deposition (2°×2.5° grid resol...,dataset,2018,2018-01-01,"{'id': 'https://openalex.org/T11588', 'display...","[{'id': 'https://openalex.org/T11588', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,17,None,NaN,"{'volume': None, 'issue': None, 'first_page': ...",NaN,NaN,NaN,None,None,None,None,University of Minnesota Digital Conservancy (U...
3,https://openalex.org/W2525336510,https://doi.org/10.13020/d6jp4s,Minnesota Land Cover Classification and Imperv...,dataset,2016,2016-01-01,"{'id': 'https://openalex.org/T13388', 'display...","[{'id': 'https://openalex.org/T13388', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,public-domain,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,12,None,NaN,"{'volume': None, 'issue': None, 'first_page': ...",NaN,NaN,NaN,None,None,None,None,University of Minnesota Digital Conservancy (U...
4,https://openalex.org/W3043928535,https://doi.org/10.13020/g1gx-y834,TrashCan 1.0 An Instance-Segmentation Labeled ...,dataset,2019,2019-06-24,"{'id': 'https://openalex.org/T12039', 'display...","[{'id': 'https://openalex.org/T12039', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4306402521', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[],[],NaN,NaN,NaN,False,12,None,NaN,"{'volume': None, 'issue': None, 'first_page': ...",NaN,NaN,NaN,None,None,None,None,University of Minnesota Digital Conservancy (U...

In [272]:
# what was , 'min', 'max'
# Create new DataFrame to concat original data from
cleaned_df = df[['id', 'doi', 'type', 'title', 'publication_year', 'publication_date', 'primary_topic', 'topics',
       'language', 'retracted', 'index location', 'is_oa',
       'oa_status', 'license', 'primary_location-source-display_name',
       'apc_list', 'apc_paid', 'fwci', 'has_fulltext','cited_by_count',
       'citation_normalized_percentile-value', 'is_in_top_1_percent',
       'is_in_top_10_percent', 'volume', 'issue', 'first_page',
       'last_page',]].copy()
cleaned_df

,id,doi,type,title,publication_year,publication_date,primary_topic,topics,language,retracted,index location,is_oa,oa_status,license,primary_location-source-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile-value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://openalex.org/W2297941261,https://doi.org/10.13020/d6g014,dataset,White-tailed deer density estimates across the...,2016,2016-01-01,"{'id': 'https://openalex.org/T10199', 'display...","[{'id': 'https://openalex.org/T10199', 'displa...",en,False,datacite,True,green,None,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://openalex.org/W2898833073,https://doi.org/10.13020/d6kx2r,dataset,Global nitrogen deposition (2°×2.5° grid resol...,2018,2018-01-01,"{'id': 'https://openalex.org/T11588', 'display...","[{'id': 'https://openalex.org/T11588', 'displa...",en,False,datacite,True,green,None,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://openalex.org/W2525336510,https://doi.org/10.13020/d6jp4s,dataset,Minnesota Land Cover Classification and Imperv...,2016,2016-01-01,"{'id': 'https://openalex.org/T13388', 'display...","[{'id': 'https://openalex.org/T13388', 'displa...",en,False,datacite,True,green,public-domain,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://openalex.org/W3043928535,https://doi.org/10.13020/g1gx-y834,dataset,TrashCan 1.0 An Instance-Segmentation Labeled ...,2019,2019-06-24,"{'id': 'https://openalex.org/T12039', 'display...","[{'id': 'https://openalex.org/T12039', 'displa...",en,False,datacite,True,green,None,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,https://openalex.org/W7137012762,https://doi.org/10.13020/m0g4-ac20,dataset,"Data for ""Effect of water suppression and meta...",2026,2026-01-01,None,[],None,False,datacite,True,green,public-domain,Data Repository for the University of Minnesota,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
732,https://openalex.org/W7140099683,https://doi.org/10.13020/qn0g-0564,dataset,Supporting data for Probing Phonon Mean-Free-P...,2026,2026-01-01,None,[],None,False,datacite,True,green,public-domain,Data Repository for the University of Minnesota,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
733,https://openalex.org/W830385225,None,dataset,"C-35, Geologic Atlas of Meeker County, Minneso...",2015,2015-01-01,"{'id': 'https://openalex.org/T13939', 'display...","[{'id': 'https://openalex.org/T13939', 'displa...",en,False,NaN,True,green,None,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,True,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
734,https://openalex.org/W89491114,None,dataset,Tracking of references with varying frequency,2014,2014-09-30,"{'id': 'https://openalex.org/T12031', 'display...","[{'id': 'https://openalex.org/T12031', 'displa...",en,False,NaN,False,closed,None,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
735,https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,"{'id': 'https://openalex.org/T11276', 'display...","[{'id': 'https://openalex.org/T11276', 'displa...",en,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [273]:
# concat original data to unnested cleaned_df
cleaned_df = pd.concat([authorships_df, cleaned_df], axis=1)
cleaned_df

,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,type,title,publication_year,publication_date,primary_topic,topics,language,retracted,index location,is_oa,oa_status,license,primary_location-source-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile-value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page
0,first,"{'id': 'https://openalex.org/A5061017744', 'di...",[],[],True,"Marenich, Aleksandr V",NaN,[],https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,middle,"{'id': 'https://openalex.org/A5053083096', 'di...",[],[],False,"Kelly, Casey P",NaN,[],https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,middle,"{'id': 'https://openalex.org/A5111863630', 'di...",[],[],False,"Thompson, Jason D",NaN,[],https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,middle,"{'id': 'https://openalex.org/A5113505750', 'di...",[],[],False,"Hawkins, Gregory D",NaN,[],https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,middle,"{'id': 'https://openalex.org/A5110699802', 'di...",[],[],False,"Chambers, Candy C",NaN,[],https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,middle,"{'id': 'https://openalex.org/A5019127857', 'di...",[],[],False,"Palka, Stephen",NaN,[],https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,"{'id': 'https://openalex.org/T11276', 'display...","[{'id': 'https://openalex.org/T11276', 'displa...",en,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
735,middle,"{'id': 'https://openalex.org/A5048502234', 'di...",[],[],False,"Piernot, Devon",NaN,[],https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,"{'id': 'https://openalex.org/T11276', 'display...","[{'id': 'https://openalex.org/T11276', 'displa...",en,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
735,middle,"{'id': 'https://openalex.org/A5006917855', 'di...",[],[],False,"Thiede, Dan",NaN,[],https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,"{'id': 'https://openalex.org/T11276', 'display...","[{'id': 'https://openalex.org/T11276', 'displa...",en,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
735,middle,"{'id': 'https://openalex.org/A5007673815', 'di...",[],[],False,"Xie, Yiquan",NaN,[],https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,"{'id': 'https://openalex.org/T11276', 'display...","[{'id': 'https://openalex.org/T11276', 'displa...",en,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
735,last,"{'id': 'https://openalex.org/A5025818352', 'di...",[],[],False,"Walz, Andrew",NaN,[],https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,"{'id': 'https://openalex.org/T11276', 'display...","[{'id': 'https://openalex.org/T11276', 'displa...",en,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [274]:
cleaned_df.iloc[736]

author_position                                                                     first
author                                  {'id': 'https://openalex.org/A5060292512', 'di...
institutions                                                                           []
countries                                                                              []
is_corresponding                                                                     True
raw_author_name                            Lee, Norman; Schrode, Katrina, M; Bee, Mark, A
raw_affiliation_strings                                                               NaN
affiliations                                                                           []
id                                                       https://openalex.org/W2745352787
doi                                                       https://doi.org/10.13020/d6xm2r
type                                                                              dataset
title                                   Nonlinear Processing of a Multicomponent Commu...
publication_year                                                                     2013
publication_date                                                               2013-04-25
primary_topic                           {'id': 'https://openalex.org/T13493', 'display...
topics                                  [{'id': 'https://openalex.org/T13493', 'displa...
language                                                                               en
retracted                                                                           False
index location                                                                   datacite
is_oa                                                                                True
oa_status                                                                           green
license                                                                              None
primary_location-source-display_name    University of Minnesota Digital Conservancy (U...
apc_list                                                                              NaN
apc_paid                                                                              NaN
fwci                                                                                  NaN
has_fulltext                                                                        False
cited_by_count                                                                          0
citation_normalized_percentile-value                                                  NaN
is_in_top_1_percent                                                                   NaN
is_in_top_10_percent                                                                  NaN
volume                                                                               None
issue                                                                                None
first_page                                                                           None
last_page                                                                            None
Name: 248, dtype: object

In [275]:
# reset index to concat with author information_df
cleaned_df = cleaned_df.reset_index()

# normalize author column
author_info_df= pd.json_normalize(cleaned_df['author'])
author_info_df = author_info_df.rename(columns={'id': 'authorships-author-author_id', 'display_name': 'authorships-author-display_name'})
author_info_df

,authorships-author-author_id,authorships-author-display_name,orcid
0,https://openalex.org/A5061017744,Aleksandr V. Marenich,https://orcid.org/0000-0003-0288-843X
1,https://openalex.org/A5053083096,Casey P. Kelly,None
2,https://openalex.org/A5111863630,Jason D. Thompson,https://orcid.org/0009-0002-4710-8505
3,https://openalex.org/A5113505750,Gregory D. Hawkins,None
4,https://openalex.org/A5110699802,Candee C. Chambers,None
...,...,...,...
2463,https://openalex.org/A5019127857,Stephen Palka,None
2464,https://openalex.org/A5048502234,Devon Piernot,None
2465,https://openalex.org/A5006917855,Dan Thiede,None
2466,https://openalex.org/A5007673815,Yiquan Xie,None
2467,https://openalex.org/A5025818352,Andrew Walz,None

In [276]:
# concat author_info_df to cleaned_df
cleaned_df = pd.concat([cleaned_df, author_info_df], axis=1).reset_index(drop=True)
cleaned_df.head()

,index,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,type,title,publication_year,publication_date,primary_topic,topics,language,retracted,index location,is_oa,oa_status,license,primary_location-source-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile-value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page,authorships-author-author_id,authorships-author-display_name,orcid
0,0,first,"{'id': 'https://openalex.org/A5061017744', 'di...",[],[],True,"Marenich, Aleksandr V",NaN,[],https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5061017744,Aleksandr V. Marenich,https://orcid.org/0000-0003-0288-843X
1,0,middle,"{'id': 'https://openalex.org/A5053083096', 'di...",[],[],False,"Kelly, Casey P",NaN,[],https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5053083096,Casey P. Kelly,None
2,0,middle,"{'id': 'https://openalex.org/A5111863630', 'di...",[],[],False,"Thompson, Jason D",NaN,[],https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5111863630,Jason D. Thompson,https://orcid.org/0009-0002-4710-8505
3,0,middle,"{'id': 'https://openalex.org/A5113505750', 'di...",[],[],False,"Hawkins, Gregory D",NaN,[],https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5113505750,Gregory D. Hawkins,None
4,0,middle,"{'id': 'https://openalex.org/A5110699802', 'di...",[],[],False,"Chambers, Candy C",NaN,[],https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5110699802,Candee C. Chambers,None

In [277]:
# normalize nested Insituttion column
institutions_df = CleanJSON('institutions', cleaned_df)

# remove list format for lineage
institutions_df['lineage'] = institutions_df['lineage'].str[0]
institutions_df

# rename columns
institutions_df = institutions_df.rename(columns={'id': 'institutions-id', 'display_name': 'institutions-display_name', 'type': 'institutions-type'})

In [278]:
# remove duplicate indices 
institutions_df = institutions_df[~institutions_df.index.duplicated(keep='first')]

# fill nan values on missinging indices
institutions_df = institutions_df.reindex(range(institutions_df.index.min(), institutions_df.index.max()+1))

In [279]:
missing_index(institutions_df)

[0, 1, 2, 3, 4, 5, 6]

In [280]:
institutions_df = institutions_df.reindex(range(0, institutions_df.index.max()+1))

In [281]:
missing_index(institutions_df)

[]

In [282]:
institutions_df.head(50)

,institutions-id,institutions-display_name,ror,country_code,institutions-type,lineage
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN
7,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580
8,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580
9,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN
45,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580
46,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580
47,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN

In [283]:
primary_topic_df = CleanJSON('primary_topic', cleaned_df)
primary_topic_df = primary_topic_df.rename(columns={'id': 'primary_topic-id', 'score': 'primary_topic-score', 'display_name': 'primary_topic-display_name', 
                                      'subfield': 'primary_topic-subfield', 'field': 'primary_topic-field', 'domain': 'primary_topic-domain'})
primary_topic_df

,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain
0,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3
0,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,Artificial Intelligence,Computer Science,Physical Sciences
1,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3
1,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,Artificial Intelligence,Computer Science,Physical Sciences
2,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3
...,...,...,...,...,...,...
2465,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,Artificial Intelligence,Computer Science,Physical Sciences
2466,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3
2466,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,Artificial Intelligence,Computer Science,Physical Sciences
2467,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3
2467,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,Artificial Intelligence,Computer Science,Physical Sciences

In [284]:
primary_topic_df = primary_topic_df[~primary_topic_df.index.duplicated(keep='first')]

primary_topic_df = primary_topic_df.reindex(range(primary_topic_df.index.min(), primary_topic_df.index.max()+1))

In [285]:
primary_topic_df

,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain
0,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3
1,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3
2,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3
3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3
4,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3
...,...,...,...,...,...,...
2463,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3
2464,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3
2465,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3
2466,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3
2467,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3

In [286]:
missing_index(primary_topic_df)

[]

In [287]:
topics_df = CleanJSON('topics', cleaned_df)
topics_df = topics_df.rename(columns={'id': 'topics-id', 'display_name': 'topics-display_name'})
topics_df

,topics-id,topics-display_name,score,subfield,field,domain
0,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,"{'id': 'https://openalex.org/subfields/1702', ...","{'id': 'https://openalex.org/fields/17', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
1,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,"{'id': 'https://openalex.org/subfields/1702', ...","{'id': 'https://openalex.org/fields/17', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
2,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,"{'id': 'https://openalex.org/subfields/1702', ...","{'id': 'https://openalex.org/fields/17', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,"{'id': 'https://openalex.org/subfields/1702', ...","{'id': 'https://openalex.org/fields/17', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
4,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,"{'id': 'https://openalex.org/subfields/1702', ...","{'id': 'https://openalex.org/fields/17', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
...,...,...,...,...,...,...
2465,https://openalex.org/T11588,Atmospheric and Environmental Gas Dynamics,0.9035,"{'id': 'https://openalex.org/subfields/2306', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
2466,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,"{'id': 'https://openalex.org/subfields/1702', ...","{'id': 'https://openalex.org/fields/17', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
2466,https://openalex.org/T11588,Atmospheric and Environmental Gas Dynamics,0.9035,"{'id': 'https://openalex.org/subfields/2306', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
2467,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,"{'id': 'https://openalex.org/subfields/1702', ...","{'id': 'https://openalex.org/fields/17', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
2467,https://openalex.org/T11588,Atmospheric and Environmental Gas Dynamics,0.9035,"{'id': 'https://openalex.org/subfields/2306', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."

In [288]:
missing_index(topics_df)

[504,
 505,
 506,
 507,
 2132,
 2133,
 2134,
 2135,
 2136,
 2137,
 2138,
 2139,
 2140,
 2141,
 2142,
 2143,
 2144,
 2145,
 2146,
 2147,
 2148,
 2149,
 2150,
 2151,
 2152,
 2153,
 2154,
 2155,
 2156,
 2157,
 2158,
 2159,
 2160,
 2161,
 2162,
 2163,
 2164,
 2165,
 2166,
 2167,
 2168,
 2169,
 2170,
 2171,
 2172,
 2173,
 2174,
 2175,
 2176,
 2177,
 2178,
 2179,
 2180,
 2181,
 2182,
 2183,
 2184,
 2185,
 2186,
 2187,
 2188,
 2189,
 2190,
 2191,
 2192,
 2193,
 2194,
 2195,
 2196,
 2197,
 2198,
 2199,
 2200,
 2201,
 2202,
 2203,
 2204,
 2205,
 2206,
 2207,
 2208,
 2209,
 2210,
 2211,
 2212,
 2213,
 2214,
 2215,
 2216,
 2217,
 2218,
 2219,
 2220,
 2221,
 2222,
 2223,
 2224,
 2225,
 2226,
 2227,
 2228,
 2229,
 2230,
 2231,
 2232,
 2233,
 2234,
 2235,
 2236,
 2237,
 2238,
 2239,
 2240,
 2241,
 2242,
 2243,
 2244,
 2245,
 2246,
 2247,
 2248,
 2249,
 2250,
 2251,
 2252,
 2253,
 2254,
 2255,
 2256,
 2257,
 2258,
 2259,
 2260,
 2261,
 2262,
 2263,
 2264,
 2265,
 2266,
 2267,
 2268,
 2269,
 2270,
 2271,
 2272,
 2273,
 2274,
 2275,
 2276,
 2277,
 2278,
 2279,
 2280,
 2281,
 2282,
 2283,
 2284,
 2285,
 2286,
 2287,
 2288,
 2289,
 2290,
 2291,
 2292,
 2293,
 2294,
 2295,
 2296,
 2297,
 2298,
 2299,
 2300,
 2301,
 2302,
 2303,
 2304,
 2305,
 2306,
 2307,
 2308,
 2309,
 2310,
 2311,
 2312,
 2313,
 2314,
 2315,
 2316,
 2317,
 2318,
 2319,
 2320,
 2321,
 2322,
 2323,
 2324,
 2325,
 2326,
 2327,
 2328,
 2329,
 2330,
 2331,
 2332,
 2333,
 2334,
 2335,
 2336,
 2337,
 2338,
 2339,
 2340,
 2341,
 2342,
 2343,
 2344,
 2345,
 2346,
 2347,
 2348,
 2349,
 2350,
 2351,
 2352,
 2353,
 2354,
 2355,
 2356,
 2357,
 2358,
 2359,
 2360,
 2361,
 2362,
 2363,
 2364,
 2365,
 2366,
 2367,
 2368,
 2369,
 2370,
 2371,
 2372,
 2373,
 2374,
 2375,
 2376,
 2377,
 2378,
 2379,
 2380,
 2381,
 2382,
 2383,
 2384,
 2385,
 2386,
 2387,
 2388,
 2389,
 2390,
 2391,
 2392,
 2393,
 2394,
 2395,
 2396,
 2397,
 2398,
 2399,
 2400,
 2401,
 2402,
 2403,
 2404,
 2405,
 2406,
 2407,
 2408,
 2409,
 2410,
 2411,
 2412,
 2413,
 2414,
 2415,
 2416,
 2417,
 2418,
 2419,
 2420,
 2421,
 2422,
 2423,
 2424,
 2425,
 2426,
 2427,
 2428,
 2429,
 2430,
 2431,
 2432,
 2433,
 2434,
 2435,
 2436,
 2437,
 2438,
 2439,
 2440,
 2441,
 2442,
 2443,
 2444,
 2445,
 2446,
 2447,
 2448,
 2449,
 2450,
 2451,
 2452,
 2468,
 2469,
 2470,
 2471,
 2472,
 2473,
 2474,
 2475,
 2476,
 2477,
 2478,
 2479,
 2480,
 2481,
 2482,
 2483,
 2484,
 2485,
 2486,
 2487,
 2488,
 2489,
 2490,
 2491,
 2492,
 2493,
 2494,
 2495,
 2496,
 2497,
 2498,
 2499,
 2500,
 2501,
 2502,
 2503,
 2504,
 2505,
 2506,
 2507,
 2508,
 2509,
 2510,
 2511,
 2512,
 2513,
 2514,
 2515,
 2516,
 2517,
 2518,
 2519,
 2520,
 2521,
 2522,
 2523,
 2524,
 2525,
 2526,
 2527,
 2528,
 2529,
 2530,
 2531,
 2532,
 2533,
 2534,
 2535,
 2536,
 2537,
 2538,
 2539,
 2540,
 2541,
 2542,
 2543,
 2544,
 2545,
 2546,
 2547,
 2548,
 2549,
 2550,
 2551,
 2552,
 2553,
 2554,
 2555,
 2556,
 2557,
 2558,
 2559,
 2560,
 2561,
 2562,
 2563,
 2564,
 2565,
 2566,
 2567,
 2568,
 2569,
 2570,
 2571,
 2572,
 2573,
 2574,
 2575,
 2576,
 2577,
 2578,
 2579,
 2580,
 2581,
 2582,
 2583,
 2584,
 2585,
 2586,
 2587,
 2588,
 2589,
 2590,
 2591,
 2592,
 2593,
 2594,
 2595,
 2596,
 2597,
 2598,
 2599,
 2600,
 2601,
 2602,
 2603,
 2604,
 2605,
 2606,
 2607,
 2608,
 2609,
 2610,
 2611,
 2612,
 2613,
 2614,
 2615,
 2616,
 2617,
 2618,
 2619,
 2620,
 2621,
 2622,
 2623,
 2624,
 2625,
 2626,
 2627,
 2628,
 2629,
 2630,
 2631,
 2632,
 2633,
 2634,
 2635,
 2636,
 2637,
 2638,
 2639,
 2640,
 2641,
 2642,
 2643,
 2644,
 2645,
 2646,
 2647,
 2648,
 2649,
 2650,
 2651,
 2652,
 2653,
 2654,
 2655,
 2656,
 2657,
 2658,
 2659,
 2660,
 2661,
 2662,
 2663,
 2664,
 2665,
 2666,
 2667,
 2668,
 2669,
 2670,
 2671,
 2672,
 2673,
 2674,
 2675,
 2676,
 2677,
 2678,
 2679,
 2680,
 2681,
 2682,
 2683,
 2684,
 2685,
 2686,
 2687,
 2688,
 2689,
 2690,
 2691,
 2692,
 2693,
 2694,
 2695,
 2696,
 2697,
 2698,
 2699,
 2700,
 2701,
 2702,
 2703,
 2704,
 2705,
 2706,
 2707,
 2708,
 2709,
 2710,
 2711,
 2712,
 2713,
 2714,
 2715,
 2716,
 2717,
 2718,
 2719,
 2720,
 2721,
 2722,
 2723,
 2724,
 2725,
 2726,
 2727,
 2728,
 2729,
 2730,
 2731,
 2732,
 2733,
 2734,
 2735,
 2736,
 2737,
 2738,
 2739,
 2740,
 2741,
 2742,
 2743,
 2744,
 2745,
 2746,
 2747,
 2748,
 2749,
 2750,
 2751,
 2752,
 2753,
 2754,
 2755,
 2756,
 2757,
 2758,
 2759,
 2760,
 2761,
 2762,
 2763,
 2764,
 2765,
 2766,
 2767,
 2768,
 2769,
 2770,
 2771,
 2772,
 2773,
 2774,
 2775,
 2776,
 2777,
 2778,
 2779,
 2780,
 2781,
 2782,
 2783,
 2784,
 2785,
 2786,
 2787,
 2788,
 2789,
 2790,
 2791,
 2792,
 2793,
 2794,
 2795,
 2796,
 2797,
 2798,
 2799,
 2800,
 2801,
 2802,
 2803,
 2804,
 2805,
 2806,
 2807,
 2808,
 2809,
 2810,
 2811,
 2812,
 2813,
 2814,
 2815,
 2816,
 2817,
 2818,
 2819,
 2820,
 2821,
 2822,
 2823,
 2824,
 2825,
 2826,
 2827,
 2828,
 2829,
 2830,
 2831,
 2832,
 2833,
 2834,
 2835,
 2836,
 2837,
 2838,
 2839,
 2840,
 2841,
 2842,
 2843,
 2844,
 2845,
 2846,
 2847,
 2848,
 2849,
 2850,
 2851,
 2852,
 2853,
 2854,
 2855,
 2856,
 2857,
 2858,
 2859,
 2860,
 2861,
 2862,
 2863,
 2864,
 2865,
 2866,
 2867,
 2868,
 2869,
 2870,
 2871,
 2872,
 2873,
 2874,
 2875,
 2876,
 2877,
 2878,
 2879,
 2880,
 2881,
 2882,
 2883,
 2884,
 2885,
 2886,
 2887,
 2888,
 2889,
 2890,
 2891,
 2892,
 2893,
 2894,
 2895,
 2896,
 2897,
 2898,
 2899,
 2900,
 2901,
 2902,
 2903,
 2904,
 2905,
 2906,
 2907,
 2908,
 2909,
 2910,
 2911,
 2912,
 2913,
 2914,
 2915,
 2916,
 2917,
 2918,
 2919,
 2920,
 2921,
 2922,
 2923,
 2924,
 2925,
 2926,
 2927,
 2928,
 2929,
 2930,
 2931,
 2932,
 2933,
 2934,
 2935,
 2936,
 2937,
 2938,
 2939,
 2940,
 2941,
 2942,
 2943,
 2944,
 2945,
 2946,
 2947,
 2948,
 2949,
 2950,
 2951,
 2952,
 2953,
 2954,
 2955,
 2956,
 2957,
 2958,
 2959,
 2960,
 2961,
 2962,
 2963,
 2964,
 2965,
 2966,
 2967,
 2968,
 2969,
 2970,
 2971,
 2972,
 2973,
 2974,
 2975,
 2976,
 2977,
 2978,
 2979,
 2980,
 2981,
 2982,
 2983,
 2984,
 2985,
 2986,
 2987,
 2988,
 2989,
 2990,
 2991,
 2992,
 2993,
 2994,
 2995,
 2996,
 2997,
 2998,
 2999,
 3000,
 3001,
 3002,
 3003,
 3004,
 3005,
 3006,
 3007,
 3008,
 3009,
 3010,
 3011,
 3012,
 3013,
 3014,
 3015,
 3016,
 3017,
 3018,
 3019,
 3020,
 3021,
 3022,
 3023,
 3024,
 3025,
 3026,
 3027,
 3028,
 3029,
 3030,
 3031,
 3032,
 3033,
 3034,
 3035,
 3036,
 3037,
 3038,
 3039,
 3040,
 3041,
 3042,
 3043,
 3044,
 3045,
 3046,
 3047,
 3048,
 3049,
 3050,
 3051,
 3052,
 3053,
 3054,
 3055,
 3056,
 3057,
 3058,
 3059,
 3060,
 3061,
 3062,
 3063,
 3064,
 3065,
 3066,
 3067,
 3068,
 3069,
 3070,
 3071,
 3072,
 3073,
 3074,
 3075,
 3076,
 3077,
 3078,
 3079,
 3080,
 3081,
 3082,
 3083,
 3084,
 3085,
 3086,
 3087,
 3088,
 3089,
 3090,
 3091,
 3092,
 3093,
 3094,
 3095,
 3096,
 3097,
 3098,
 3099,
 3100,
 3101,
 3102,
 3103,
 3104,
 3105,
 3106,
 3107,
 3108,
 3109,
 3110,
 3111,
 3112,
 3113,
 3114,
 3115,
 3116,
 3117,
 3118,
 3119,
 3120,
 3121,
 3122,
 3123,
 3124,
 3125,
 3126,
 3127,
 3128,
 3129,
 3130,
 3131,
 3132,
 3133,
 3134,
 3135,
 3136,
 3137,
 3138,
 3139,
 3140,
 3141,
 3142,
 ...]

In [289]:
topics_df = topics_df[~topics_df.index.duplicated(keep='first')]

topics_df = topics_df.reindex(range(topics_df.index.min(), topics_df.index.max()+1))

In [305]:
missing_index(topics_df)

[]

In [290]:
subfield_df = pd.json_normalize(topics_df['subfield'])
field_df = pd.json_normalize(topics_df['field'])
domain_df = pd.json_normalize(topics_df['domain'])

# rename 
subfield_df = subfield_df.rename(columns={'id': 'topics-subfield-id', 'display_name': 'topics-subfield-display_name'})
field_df = field_df.rename(columns={'id': 'topics-field-id', 'display_name': 'topics-field-display_name'})
domain_df = domain_df.rename(columns={'id': 'topics-domain-id', 'display_name': 'topics-domain-display_name'})

field_df

                     topics-field-id topics-field-display_name
0     https://openalex.org/fields/17          Computer Science
1     https://openalex.org/fields/17          Computer Science
2     https://openalex.org/fields/17          Computer Science
3     https://openalex.org/fields/17          Computer Science
4     https://openalex.org/fields/17          Computer Science
...                              ...                       ...
2463  https://openalex.org/fields/17          Computer Science
2464  https://openalex.org/fields/17          Computer Science
2465  https://openalex.org/fields/17          Computer Science
2466  https://openalex.org/fields/17          Computer Science
2467  https://openalex.org/fields/17          Computer Science

[2468 rows x 2 columns]

In [291]:
topics_df = topics_df[['topics-id', 'topics-display_name']]

In [292]:
topics_df=topics_df.reset_index(drop=True)
topics_df = pd.concat([topics_df, subfield_df], axis=1).reset_index(drop=True)
topics_df = pd.concat([topics_df, field_df], axis=1).reset_index(drop=True)
topics_df = pd.concat([topics_df, domain_df], axis=1).reset_index(drop=True)
topics_df

,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name
0,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
1,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
2,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
4,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
...,...,...,...,...,...,...,...,...
2463,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
2464,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
2465,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
2466,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
2467,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences

In [293]:
# concat insitution_df and topics_df
merged_list = [institutions_df, primary_topic_df, topics_df]
merged_df = pd.concat(merged_list, axis=1)
merged_df

,institutions-id,institutions-display_name,ror,country_code,institutions-type,lineage,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name
0,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
1,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
2,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
3,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
4,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2463,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
2464,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
2465,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
2466,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
2467,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences

In [294]:
unnested_df = cleaned_df.copy()
unnested_df

,index,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,type,title,publication_year,publication_date,primary_topic,topics,language,retracted,index location,is_oa,oa_status,license,primary_location-source-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile-value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page,authorships-author-author_id,authorships-author-display_name,orcid
0,0,first,"{'id': 'https://openalex.org/A5061017744', 'di...",[],[],True,"Marenich, Aleksandr V",NaN,[],https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5061017744,Aleksandr V. Marenich,https://orcid.org/0000-0003-0288-843X
1,0,middle,"{'id': 'https://openalex.org/A5053083096', 'di...",[],[],False,"Kelly, Casey P",NaN,[],https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5053083096,Casey P. Kelly,None
2,0,middle,"{'id': 'https://openalex.org/A5111863630', 'di...",[],[],False,"Thompson, Jason D",NaN,[],https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5111863630,Jason D. Thompson,https://orcid.org/0009-0002-4710-8505
3,0,middle,"{'id': 'https://openalex.org/A5113505750', 'di...",[],[],False,"Hawkins, Gregory D",NaN,[],https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5113505750,Gregory D. Hawkins,None
4,0,middle,"{'id': 'https://openalex.org/A5110699802', 'di...",[],[],False,"Chambers, Candy C",NaN,[],https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,"{'id': 'https://openalex.org/T12157', 'display...","[{'id': 'https://openalex.org/T12157', 'displa...",en,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5110699802,Candee C. Chambers,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2463,735,middle,"{'id': 'https://openalex.org/A5019127857', 'di...",[],[],False,"Palka, Stephen",NaN,[],https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,"{'id': 'https://openalex.org/T11276', 'display...","[{'id': 'https://openalex.org/T11276', 'displa...",en,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,0,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5019127857,Stephen Palka,None
2464,735,middle,"{'id': 'https://openalex.org/A5048502234', 'di...",[],[],False,"Piernot, Devon",NaN,[],https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,"{'id': 'https://openalex.org/T11276', 'display...","[{'id': 'https://openalex.org/T11276', 'displa...",en,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,0,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5048502234,Devon Piernot,None
2465,735,middle,"{'id': 'https://openalex.org/A5006917855', 'di...",[],[],False,"Thiede, Dan",NaN,[],https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,"{'id': 'https://openalex.org/T11276', 'display...","[{'id': 'https://openalex.org/T11276', 'displa...",en,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,0,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5006917855,Dan Thiede,None
2466,735,middle,"{'id': 'https://openalex.org/A5007673815', 'di...",[],[],False,"Xie, Yiquan",NaN,[],https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,"{'id': 'https://openalex.org/T11276', 'display...","[{'id': 'https://openalex.org/T11276', 'displa...",en,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,0,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5007673815,Yiquan Xie,None
2467,735,last,"{'id': 'https://openalex.org/A5025818352', 'di...",[],[],False,"Walz, Andrew",NaN,[],https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,"{'id': 'https://openalex.org/T11276', 'display...","[{'id': 'https://openalex.org/T11276', 'displa...",en,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,NaN,NaN,NaN,False,0,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5025818352,Andrew Walz,None

In [295]:
unnested_df.columns

Index(['index', 'author_position', 'author', 'institutions', 'countries',
       'is_corresponding', 'raw_author_name', 'raw_affiliation_strings',
       'affiliations', 'id', 'doi', 'type', 'title', 'publication_year',
       'publication_date', 'primary_topic', 'topics', 'language', 'retracted',
       'index location', 'is_oa', 'oa_status', 'license',
       'primary_location-source-display_name', 'apc_list', 'apc_paid', 'fwci',
       'has_fulltext', 'cited_by_count',
       'citation_normalized_percentile-value', 'is_in_top_1_percent',
       'is_in_top_10_percent', 'volume', 'issue', 'first_page', 'last_page',
       'authorships-author-author_id', 'authorships-author-display_name',
       'orcid'],
      dtype='object')

In [ ]:
unnested_df = unnested_df[['author_position', 'countries',
       'is_corresponding', 'raw_author_name', 'raw_affiliation_strings',
       'id', 'doi', 'type', 'title', 'publication_year',
       'publication_date', 'language', 'apc_list', 'apc_paid',
       'fwci', 'has_fulltext', 'cited_by_count',
       'citation_normalized_percentile-value', 'is_in_top_1_percent',
       'is_in_top_10_percent', 'volume', 'issue', 'first_page',
       'last_page', 'retracted', 'index location',
       'is_oa', 'oa_status', 'license', 'primary_location-source-display_name', 'authorships-author-author_id',
       'authorships-author-display_name', 'orcid']]
unnested_df

,author_position,countries,is_corresponding,raw_author_name,raw_affiliation_strings,id,doi,type,title,publication_year,publication_date,language,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile-value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page,retracted,index location,is_oa,oa_status,license,primary_location-source-display_name,authorships-author-author_id,authorships-author-display_name,orcid
0,first,[],True,"Marenich, Aleksandr V",NaN,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5061017744,Aleksandr V. Marenich,https://orcid.org/0000-0003-0288-843X
1,middle,[],False,"Kelly, Casey P",NaN,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5053083096,Casey P. Kelly,None
2,middle,[],False,"Thompson, Jason D",NaN,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5111863630,Jason D. Thompson,https://orcid.org/0009-0002-4710-8505
3,middle,[],False,"Hawkins, Gregory D",NaN,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5113505750,Gregory D. Hawkins,None
4,middle,[],False,"Chambers, Candy C",NaN,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5110699802,Candee C. Chambers,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2463,middle,[],False,"Palka, Stephen",NaN,https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,en,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5019127857,Stephen Palka,None
2464,middle,[],False,"Piernot, Devon",NaN,https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,en,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5048502234,Devon Piernot,None
2465,middle,[],False,"Thiede, Dan",NaN,https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,en,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5006917855,Dan Thiede,None
2466,middle,[],False,"Xie, Yiquan",NaN,https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,en,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5007673815,Yiquan Xie,None
2467,last,[],False,"Walz, Andrew",NaN,https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,en,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5025818352,Andrew Walz,None

In [297]:
unnested_df = pd.concat([unnested_df, merged_df], axis=1)
unnested_df

,author_position,countries,is_corresponding,raw_author_name,raw_affiliation_strings,id,doi,type,title,publication_year,publication_date,language,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile-value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page,retracted,index location,is_oa,oa_status,license,primary_location-source-display_name,authorships-author-author_id,authorships-author-display_name,orcid,institutions-id,institutions-display_name,ror,country_code,institutions-type,lineage,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name
0,first,[],True,"Marenich, Aleksandr V",NaN,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5061017744,Aleksandr V. Marenich,https://orcid.org/0000-0003-0288-843X,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
1,middle,[],False,"Kelly, Casey P",NaN,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5053083096,Casey P. Kelly,None,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
2,middle,[],False,"Thompson, Jason D",NaN,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5111863630,Jason D. Thompson,https://orcid.org/0009-0002-4710-8505,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
3,middle,[],False,"Hawkins, Gregory D",NaN,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5113505750,Gregory D. Hawkins,None,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
4,middle,[],False,"Chambers, Candy C",NaN,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by-nc-nd,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5110699802,Candee C. Chambers,None,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2463,middle,[],False,"Palka, Stephen",NaN,https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,en,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5019127857,Stephen Palka,None,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
2464,middle,[],False,"Piernot, Devon",NaN,https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,en,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5048502234,Devon Piernot,None,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
2465,middle,[],False,"Thiede, Dan",NaN,https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,en,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5006917855,Dan Thiede,None,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
2466,middle,[],False,"Xie, Yiquan",NaN,https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,en,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5007673815,Yiquan Xie,None,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences
2467,last,[],False,"Walz, Andrew",NaN,https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,en,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,datacite,True,green,cc-by,University of Minnesota Digital Conservancy (U...,https://openalex.org/A5025818352,Andrew Walz,None,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences

In [298]:
# check for nan authors
unnested_df['authorships-author-display_name'].isnull().values.any()

False

In [299]:
# remove rows where authors are NaN
#unnested_df = unnested_df.iloc[:10568]
#unnested_df

In [300]:
unnested_df.columns

Index(['author_position', 'countries', 'is_corresponding', 'raw_author_name',
       'raw_affiliation_strings', 'id', 'doi', 'type', 'title',
       'publication_year', 'publication_date', 'language', 'apc_list',
       'apc_paid', 'fwci', 'has_fulltext', 'cited_by_count',
       'citation_normalized_percentile-value', 'is_in_top_1_percent',
       'is_in_top_10_percent', 'volume', 'issue', 'first_page', 'last_page',
       'retracted', 'index location', 'is_oa', 'oa_status', 'license',
       'primary_location-source-display_name', 'authorships-author-author_id',
       'authorships-author-display_name', 'orcid', 'institutions-id',
       'institutions-display_name', 'ror', 'country_code', 'institutions-type',
       'lineage', 'primary_topic-id', 'primary_topic-display_name',
       'primary_topic-score', 'primary_topic-subfield', 'primary_topic-field',
       'primary_topic-domain', 'topics-id', 'topics-display_name',
       'topics-subfield-id', 'topics-subfield-display_name', 'topics-field-id',
       'topics-field-display_name', 'topics-domain-id',
       'topics-domain-display_name'],
      dtype='object')

In [301]:
unnested_df = unnested_df[['id', 'doi', 'type', 'institutions-type', 'title', 'publication_year', 'publication_date', 'language', 
       'authorships-author-author_id','authorships-author-display_name', 'author_position', 'orcid',
       'primary_topic-id', 'primary_topic-display_name', 'primary_topic-score', 'primary_topic-subfield', 'primary_topic-field',
       'primary_topic-domain', 'topics-id', 'topics-display_name', 'topics-subfield-id', 'topics-subfield-display_name', 
       'topics-field-id', 'topics-field-display_name', 'topics-domain-id','topics-domain-display_name', 
       'apc_list', 'apc_paid', 'fwci', 'has_fulltext', 'cited_by_count', 'citation_normalized_percentile-value', 
       'is_in_top_1_percent', 'is_in_top_10_percent', 'volume', 'issue', 'first_page', 'last_page', 
       'index location', 'primary_location-source-display_name',
       'retracted', 'index location', 'primary_location-source-display_name', 'is_oa', 'oa_status', 'license',  
       'institutions-id', 'institutions-display_name', 'raw_affiliation_strings',  'country_code', 'ror', 'lineage']]
unnested_df.head()

,id,doi,type,institutions-type,title,publication_year,publication_date,language,authorships-author-author_id,authorships-author-display_name,author_position,orcid,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile-value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page,index location,primary_location-source-display_name,retracted,index location,primary_location-source-display_name,is_oa,oa_status,license,institutions-id,institutions-display_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5061017744,Aleksandr V. Marenich,first,https://orcid.org/0000-0003-0288-843X,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
1,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5053083096,Casey P. Kelly,middle,None,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
2,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5111863630,Jason D. Thompson,middle,https://orcid.org/0009-0002-4710-8505,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
3,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5113505750,Gregory D. Hawkins,middle,None,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
4,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5110699802,Candee C. Chambers,middle,None,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN

In [302]:
unnested_df['authorships-author-display_name'].isnull().values.any()

False

In [303]:
unnested_df.head(10)

,id,doi,type,institutions-type,title,publication_year,publication_date,language,authorships-author-author_id,authorships-author-display_name,author_position,orcid,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile-value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page,index location,primary_location-source-display_name,retracted,index location,primary_location-source-display_name,is_oa,oa_status,license,institutions-id,institutions-display_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5061017744,Aleksandr V. Marenich,first,https://orcid.org/0000-0003-0288-843X,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
1,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5053083096,Casey P. Kelly,middle,None,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
2,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5111863630,Jason D. Thompson,middle,https://orcid.org/0009-0002-4710-8505,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
3,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5113505750,Gregory D. Hawkins,middle,None,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
4,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5110699802,Candee C. Chambers,middle,None,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
5,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5016283052,David J. Giesen,middle,None,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
6,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5024124704,Paul Winget,middle,https://orcid.org/0000-0002-3443-7556,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
7,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,education,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5048985028,Christopher J. Cramer,middle,https://orcid.org/0000-0001-5048-1859,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,https://openalex.org/I2800403580,University of Minnesota System,University of Minnesota,US,https://ror.org/03grvy078,https://openalex.org/I2800403580
8,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,education,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5061717048,Donald G. Truhlar,last,https://orcid.org/0000-0002-7742-7294,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,None,None,None,None,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,https://openalex.org/I2800403580,University of Minnesota System,University of Minnesota,US,https://ror.org/03grvy078,https://openalex.org/I2800403580
9,https://openalex.org/W2297941261,https://doi.org/10.13020/d6g014,dataset,NaN,White-tailed deer density estimates across the...,2016,2016-01-01,en,https://openalex.org/A5014726860,Brian F. Walters,first,https://orcid.org/0000-0001-7408-9704,https://openalex.org/T10199,Wildlife Ecology and Conservation,0.9984,https://openalex.org/subfields/2303,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10199,Wildlife Ecology and Conservation,https://openalex.org/subfields/2303,Ecology,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,28,NaN,NaN,NaN,None,None,None,None,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,None,NaN,NaN,NaN,NaN,NaN,NaN

In [304]:
unnested_df.to_csv(str(datetime.datetime.today()).split()[0] +'-Source.csv')