In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('2026-04-22-UMN-Source.csv', index_col=0)

In [5]:
pd.set_option("display.max_columns", 55)

In [6]:
df.columns

Index(['id', 'doi', 'type', 'institutions-type', 'title', 'publication_year',
       'publication_date', 'language', 'authorships-author-author_id',
       'authorships-author-display_name', 'author_position', 'orcid',
       'primary_topic-id', 'primary_topic-display_name', 'primary_topic-score',
       'primary_topic-subfield', 'primary_topic-field', 'primary_topic-domain',
       'topics-id', 'topics-display_name', 'topics-subfield-id',
       'topics-subfield-display_name', 'topics-field-id',
       'topics-field-display_name', 'topics-domain-id',
       'topics-domain-display_name', 'apc_list', 'apc_paid', 'fwci',
       'has_fulltext', 'cited_by_count', 'volume', 'issue', 'first_page',
       'last_page', 'index location', 'primary_location-source-display_name',
       'retracted', 'index location.1',
       'primary_location-source-display_name.1', 'is_oa', 'oa_status',
       'license', 'institutions-id', 'institutions-display_name',
       'raw_affiliation_strings', 'country_code', 'ror', 'lineage'],
      dtype='object')

In [ ]:
df.head()

,id,doi,type,institutions-type,title,publication_year,publication_date,language,authorships-author-author_id,authorships-author-display_name,author_position,orcid,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,index location,primary_location-source-display_name,retracted,index location.1,primary_location-source-display_name.1,is_oa,oa_status,license,institutions-id,institutions-display_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5061017744,Aleksandr V. Marenich,first,https://orcid.org/0000-0003-0288-843X,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
1,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5053083096,Casey P. Kelly,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
2,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5111863630,Jason D. Thompson,middle,https://orcid.org/0009-0002-4710-8505,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
3,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5113505750,Gregory D. Hawkins,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
4,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,"Chambers, Candy C",middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,datacite,University of Minnesota Digital Conservancy (U...,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df['ror'].isna().sum(), df['orcid'].isna().sum()

(2177, 872)

In [30]:
(df['ror'].isna() & df['orcid'].isna()).sum()

767

In [63]:
df['ror'].isna().groupby(df['publication_year']).sum().reset_index().sort_values(by=['ror'], ascending=False).reset_index(drop=True)

    publication_year  ror
0               2019  296
1               2018  281
2               2017  214
3               2015  187
4               2016  186
5               2020  185
6               2013  142
7               2021  135
8               2014  133
9               2025  104
10              2012   53
11              2010   49
12              2026   35
13              2009   25
14              2006   21
15              1983   13
16              2011   13
17              1993   12
18              2007   12
19              1973   10
20              2024    9
21              2008    7
22              1998    7
23              2022    5
24              2005    5
25              1975    5
26              1959    4
27              1990    4
28              2004    4
29              1964    4
30              2001    4
31              2003    3
32              1979    2
33              2002    2
34              1970    1
35              1969    1
36              1966    1
37              1971    1
38              1972    1
39              1912    1
40              2023    0

In [ ]:
topics_display_name_ror = df['ror'].isna().groupby(df['topics-display_name']).sum().reset_index().sort_values(by=['ror'], ascending=False)
topics_display_name_ror.head(15).reset_index(drop=True)

                            topics-display_name  ror
306              Smoking Behavior and Cessation  102
227  Nanopore and Nanochannel Transport Studies   71
121         Fish Ecology and Management Studies   39
275           Rangeland and Wildlife Management   36
87               DNA and Nucleic Acid Chemistry   35
3            3D Printing in Biomedical Research   34
316     Species Distribution and Climate Change   33
132               Forest ecology and management   33
362     Wheat and Barley Genetics and Pathology   31
40              Archaeology and Natural History   26
39    Aquatic Invertebrate Ecology and Behavior   24
282       Remote Sensing and LiDAR Applications   24
88                         Data Analysis with R   23
137  Genetic and phenotypic traits in livestock   21
148  Groundwater flow and contamination studies   19

In [ ]:
topics_subfield_display_name_ror = df['ror'].isna().groupby(df['topics-subfield-display_name']).sum().reset_index().sort_values(by=['ror'], ascending=False)
topics_subfield_display_name_ror.head(15).reset_index(drop=True)

                    topics-subfield-display_name  ror
0                                        Ecology  153
1                         Biomedical Engineering  139
2                              Molecular Biology  132
3                                  Plant Science  111
4                                     Physiology  102
5                        Artificial Intelligence   93
6              Nature and Landscape Conservation   76
7                      Environmental Engineering   75
8                            Materials Chemistry   65
9                    Global and Planetary Change   48
10                                      Genetics   44
11  Ecology, Evolution, Behavior and Systematics   37
12                  Water Science and Technology   34
13                           Ecological Modeling   33
14                         Aerospace Engineering   30

In [61]:

topics_field_display_name_ror = df['ror'].isna().groupby(df['topics-field-display_name']).sum().reset_index().sort_values(by=['ror'], ascending=False)
topics_field_display_name_ror.head(15).reset_index(drop=True)

                       topics-field-display_name  ror
0                          Environmental Science  498
1                                    Engineering  277
2   Biochemistry, Genetics and Molecular Biology  211
3           Agricultural and Biological Sciences  209
4                               Computer Science  153
5                                       Medicine  147
6                                Social Sciences  101
7                              Materials Science   96
8                                      Chemistry   69
9                   Earth and Planetary Sciences   45
10                                    Psychology   32
11           Economics, Econometrics and Finance   25
12                         Physics and Astronomy   25
13                            Health Professions   22
14                          Chemical Engineering   19